### ISSUE TITLE
Sword RAM Requirements

### ISSUE THREAD

**Issue by cruizperez** [rvaser/sword#3]
Hi!
I have a quite large database I am working on ~64GB with approximately 140 million protein sequences. When I try to run sword using this database I get a "segmentation fault (core dumped)" error. I can run a small test using a 10 sequence-database and a couple of sequences, which is successful as well as using a moderately large database (~264Mb and ~500000 sequences). For the larger database I am using 90GB RAM but I am still getting the same error. What would be the amount of RAM required depending on the database/threads used?
The command I used is: sword -i Test_Query.faa -j Large_DB.faa -o Test.sword -f bm8 -v 1.0 -a 1 -k 5 -c 15000 -T 0 -t 5

**Comment by rvaser** [comment]
Hello,
can you somehow check if there are any proteins in your database that are longer than 65k? I did not have time to fix that yet as it needs a lot of work.

Best regards,
Robert

**Comment by cruizperez** [comment]
Hi Robert,
Thanks for your quick response. I was "sure" my database had no long sequences but I was mistaken. I was able to run my queues without issues this time. Nonetheless, I wanted to ask you if you have a rule of thumb on how much RAM per thread is recommended depending on the size of the DB? Thanks again!
Carlos

**Comment by rvaser** [comment]
Hi Carlos,
the memory consumption shouldn't be much as I am processing the database 1GB at a time and hashing queries (which are quite smaller tha  the database). Each thread searches a part of that GB where it creates a hash from a fixed amount of queries. For each query it stores at most 30k best candidates (2 integers) at a time, which is around 0.2 MB. As proteins are at average small (say 1k), around 1k of them fits in the hash which totals at 200MB per thread (at most).

Best regards,
Robert

**Comment by cruizperez** [comment]
Thanks a lot Robert! Works like a charm!
Carlos
